"""Sync schema for outreach engine

Revision ID: 4cc146a41d98
Revises: 3113281c1102
Create Date: 2026-03-08 16:03:34.758540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cc146a41d98'
down_revision: Union[str, None] = '3113281c1102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('monthly_credit_limit', sa.Integer(), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sending_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_encryption', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('wait_days', sa.Integer(), nullable=True),
    sa.Column('template_subject', sa.String(length=500), nullable=True),
    sa.Column('template_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('total_requested', sa.Integer(), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=True),
    sa.Column('total_inserted', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_rate_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sending_account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('emails_sent_today', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sending_account_id'], ['sending_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_email_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_email_id'], ['campaign_emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign_emails', sa.Column('sequence_step_id', sa.UUID(), nullable=True))
    op.add_column('campaign_emails', sa.Column('message_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_campaign_emails_message_id'), 'campaign_emails', ['message_id'], unique=False)
    op.create_foreign_key(None, 'campaign_emails', 'sequence_steps', ['sequence_step_id'], ['id'], ondelete='SET NULL')
    op.drop_column('campaign_emails', 'updated_at')
    op.add_column('campaigns', sa.Column('sequence_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'sequences', ['sequence_id'], ['id'], ondelete='SET NULL')
    op.add_column('leads', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('leads', sa.Column('current_step_number', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'leads', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.add_column('worker_logs', sa.Column('error_logs', sa.Text(), nullable=True))
    op.drop_column('worker_logs', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_logs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('worker_logs', 'error_logs')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'next_action_at')
    op.drop_column('leads', 'current_step_number')
    op.drop_column('leads', 'linkedin_url')
    op.drop_column('leads', 'company')
    op.drop_column('leads', 'title')
    op.drop_column('leads', 'email_verified')
    op.drop_column('leads', 'last_name')
    op.drop_column('leads', 'first_name')
    op.drop_column('leads', 'campaign_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'sequence_id')
    op.add_column('campaign_emails', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'campaign_emails', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_emails_message_id'), table_name='campaign_emails')
    op.drop_column('campaign_emails', 'message_id')
    op.drop_column('campaign_emails', 'sequence_step_id')
    op.drop_table('email_replies')
    op.drop_table('provider_rate_limits')
    op.drop_table('lead_generation_jobs')
    op.drop_table('sequence_steps')
    op.drop_table('sending_accounts')
    op.drop_table('usage_tracking')
    op.drop_table('subscriptions')
    op.drop_table('sequences')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
