"""Add AI integrations and usage fields to Organization

Revision ID: a2a27dd8a044
Revises: 4cc146a41d98
Create Date: 2026-03-12 18:21:59.650742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a27dd8a044'
down_revision: Union[str, None] = '4cc146a41d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('apify_api_key', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('serpapi_api_key', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('openrouter_api_key', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('default_llm_model', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('ai_usage_tokens', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('ai_usage_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'ai_usage_limit')
    op.drop_column('organizations', 'ai_usage_tokens')
    op.drop_column('organizations', 'default_llm_model')
    op.drop_column('organizations', 'openrouter_api_key')
    op.drop_column('organizations', 'serpapi_api_key')
    op.drop_column('organizations', 'apify_api_key')
    # ### end Alembic commands ###
